### ISSUE TITLE
Spacing is removed on anonymous procs

### ISSUE THREAD

**Issue by ire4ever1190** [arnetheduck/nph#22]
The spacing before the parenthesis in an anonymous proc is removed
```nim
type EventCallback = proc (timeReceived: Time)
# Becomes
type EventCallback = proc(timeReceived: Time)

app.handleRoute("/test") do ():
  discard
# Becomes
app.handleRoute("/test") do():
  discard
```

**Comment by ire4ever1190** [comment]
Seems to be due to the removal of the [putWithSpace](https://github.com/nim-lang/Nim/blob/devel/compiler/renderer.nim#L1539). Is this intended style?

**Comment by arnetheduck** [comment]
Indeed - the space there doesn't seem to serve any purpose - we don't put a space after the function name for example.

**Comment by ire4ever1190** [comment]
While not explicitly said, [NEP1 does have a space in the one of the examples](https://nim-lang.org/docs/nep1.html#style-guidelines-conventions-for-multiminusline-statements-and-expressions) (Although the status guide does have a [counterexample](https://status-im.github.io/nim-style-guide/language.proctypes.html).

IMO having the space makes sense since you'd have a space before the name so when it is empty it'd be `"proc " + "" + "(params)"`
