### ISSUE TITLE
Does not compile on windows.

### ISSUE THREAD

**Issue by treeform** [arnetheduck/nph#4]
```C:\p\nph\src\phmsgs.nim(111, 15) Error: expression 'canonicalCase(string(canon))' is of type 'string' and has to be used (or discarded)```

I think this code is invalid when FileSystemCaseSensitive is false like on windows:

```nim
proc canonicalCase(path: var string) {.inline.} =
  ## the idea is to only use this for checking whether a path is already in
  ## the table but otherwise keep the original case
  when FileSystemCaseSensitive:
    discard
  else:
    toLowerAscii(path)
```

**Comment by treeform** [comment]
work around ```nim
    path = toLowerAscii(path)
```
in the last branch

**Comment by arnetheduck** [comment]
#5
