### ISSUE TITLE
Use vertical import alignment

### ISSUE THREAD

**Issue by Ivansete-status** [arnetheduck/nph#46]
When using the `nph` in `nwaku` we realised that the import formatting is horizontal but we'd prefer to have it in vertical style.

Reasons:
1. Easier to read
2. Easier to perform comparisons

![image](https://github.com/arnetheduck/nph/assets/128452529/4889d4d7-e299-41ae-8da5-8feef617b193)

https://github.com/waku-org/nwaku/pull/2396#discussion_r1478374329

**Comment by arnetheduck** [comment]
try `import ../common/[nimchronos, enr], ".."/[waku_core, waku_enr]` etc for a less repetitive import style - when you have more than a few (aka it becomes hard to read), it'll line up like you want it to (on behalf of being [complex](https://arnetheduck.github.io/nph/style.html#lists).

See also https://arnetheduck.github.io/nph/faq.html#what-features-will-likely-not-be-added about import ordering.

**Comment by arnetheduck** [comment]
Closing this since the suggested style can work around it - pls reopen if there are other pathological imports
