### ISSUE TITLE
bug: inline comments get automatically removed

### ISSUE THREAD

**Issue by Ivansete-status** [arnetheduck/nph#47]
When starting to use `nph` in `nwaku`, SP detected that inline comments are being automatically erased.

![image](https://github.com/arnetheduck/nph/assets/128452529/06b4ce9d-b37e-4b51-bde9-b21d7ff3197f)

https://github.com/waku-org/nwaku/pull/2396#discussion_r1478370777

```
  let predicate = proc(record: waku_enr.Record): bool =
    bootnodes.contains(record) or # Temp. Bootnode exception
    (
      # one comment
      record.getCapabilities().len > 0 and   ### THIS COMMENT CAN'T BE ADDED
      nodeShard.shardIds.anyIt(record.containsShard(nodeShard.clusterId, it))
    ) #RFC 64 guideline
 ```

Thanks in advance!

**Comment by SionoiS** [comment]
I guess we'll have to put the comments above now. May be fine if the comments move slightly but not if erased.
