### ISSUE TITLE
trailing comma in collections

### ISSUE THREAD

**Issue by Archargelod** [arnetheduck/nph#57]
Please, consider not removing a trailing comma for multiline collections. Nim simply ignores it.
Having a comma at the end of every element makes it easier to add, move and sort elements (e.g. with Vim).

Example:
```Nim
var arr = [
  "zbc123looooooooooong line",
  "abc123looooooooooong line",
  "abd123looooooooooong line",
  "bbd123looooooooooong line",
]
```

Formatted with nph:
```Nim
var arr = [
  "zbc123looooooooooong line",
  "abc123looooooooooong line",
  "abd123looooooooooong line",
  "bbd123looooooooooong line"
]
```

Now If you have to copy or move the last line or add elements after it - you can often forget to put a comma.
Is there a downside to having a trailing comma?
I don't see any.

**Comment by arnetheduck** [comment]
Here's the actual formatting of that example (with nph-0.4.1):

```nim
var arr = [
  "zbc123looooooooooong line", "abc123looooooooooong line", "abd123looooooooooong line",
  "bbd123looooooooooong line"
]
```

This is a simple list, so the short form is used - the question then becomes, should trailing comma be used for short-form lists, and when?

**Comment by Archargelod** [comment]
@arnetheduck, sorry I didn't test this particular example, here's one that should format into the long form on v0.4.1:
```Nim
let arr = [
  "string over 40 characters long___________",
  "string over 40 characters long___________",
]
```

One line collections doesn't benefit from trailing comma much. It also looks a bit out of place:
```Nim
let shortList = ["foo", "bar", "baz",]
```

But in your example, I believe, making it consistent with the long form is the best choice:
```Nim
var arr = [
  "zbc123looooooooooong line", "abc123looooooooooong line", "abd123looooooooooong line",
  "bbd123looooooooooong line",
]
```

**Comment by arnetheduck** [comment]
Your first example is actually a multi-line short form given that all entries are simple (even if they all happen to be long such that only one fits per line).

For long form, it's actually a no-brainer, but the extra comma does end up looking a bit out of place for multi-line short forms, ie:

```nim
var arr = functionacall(
  "zbc123looooooooooong line", "abc123looooooooooong line", "abd123looooooooooong line",
  "bbd123looooooooooong line",
)

let x = a in {
  "zbc123looooooooooong line", "abc123looooooooooong line", "abd123looooooooooong line",
  "bbd123looooooooooong line",
}
```

**Comment by arnetheduck** [comment]
Need to think a bit more about the short form - reopening for now but feel free to close as well.

**Comment by Archargelod** [comment]
For reference, I tried this feature in other opinionated formatters, mentioned in the Readme:

prettier: 
- no compact multi-line lists, lists longer than 1 line always expand to 1-item per line form.
- trailing comma in multi-line lists by default (has option to disable it)

black:
- no compact multi-line lists, lists longer than 1 line always expand to 1-item per line form.
- short lists with trailing comma always expand to 1-item per line form ([magic trailing comma](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#the-magic-trailing-comma))
- you can't disable trailing comma

clang-format:
- tries to fit as many list items on each line
- trailing comma forces 1-item per line form
- trailing comma is optional, but always respected (even with a single element)

**Comment by arnetheduck** [comment]
> prettier

[prettier](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUwA5tXHLlM-gLz4A6IABalyggDT5W7eHV74A5IKq06ghZIDOOEghjzUAQxKa4k6AFkI6UwHkAbnGriAvgEp8wflG-5IUTX0bJwBJOk15AG1ffAB2ACYAZgAWAE5E+NTkgEZxGISU9PiE+LyofDiktIzE7NL8qqL0xLKKgur4gA4c1srCjOyANkHe9qLulob+zNjO0caM5MSRqY7Bztj56fjB1K2OgFZYyfK+jtTsk7aFruP9otjkudWixIPk+4GDq7Oi7M7ci8MllNkD4gdBj8xjV4h8wakDvVTtCup0Dp9MtlAcibrtnjjtk8MbFBnCCR0ltjrtMAVTfjVkmTqR00eiwUsAAwYxKpFbkpoAjEHLIYy50lFPPZgg6I0VDDGdRJQm6I8U3cFI5lFA4c5XTd5csGddLE5YY3lS-kDZJsq2ZcEYnKgu0pJn0+LZDn4rUDQZq6axQPm2L+jrZYWig7e92pL1CrEKknE9YYrpulGkw0ujmWn07A6hor2hWpaMotOpjmFjI6vl5wbvBXJLN5pXp9XJOvuxJJsE8ss3EPt6aXYcUt6iwXwzot93CsevXmijmzlGPPUsupCxUYwbxTXumerm61Y8jhPSnvEgvm+JnlkJYkrp8HjMy+O2vOZTreAC6AG5vG8FwQHEEAIAAB1waBNGQUBDGoagIAAdwABQQhBYJQYxkMMABPWCwIAI2oQwwAAaw4ABlQwAFs4AAGRwKA4GQIwTDMEASLIyiYCoiCyOY5hkBgah0E40xaJwESxM4uAAA8IKcHB6NgYwABUnCgBCcDgLD2NMMDtC4XQAEV0AgeA2OMQyQAAK00eSqKEsyLKspADM4gBHNy4FQpCIKwkBDE0ABaFi4DoSLQJAUTDB0ISAGEIFo2jDGQYKyBi4zmF0ABBGBRJwIj0HgVCnCYljrI4sChBgWiSAoIQcHgTQBLAOAqMwlqcHsFq8IysBNEIkB7HEkIoCi2AqLAagcCgvLJqomA8N0arbIgpDTAoUiIIyza9KcRwYuY0xqBgfzDGYNL1s4gTqDOjKiMMIjSBizbmJgCgcDoGAhGQGcwLYHycDYS7rvSjybM4mAXu+37-qQUoQGCdSXv06GwLgWjXroKK6AYwwuHQK64AAMRoNLCqEjLDFKiAQBcFwgA) does the "short-list" trick for numbers (not for strings / identifiers though).

They do add a trailing in this case.
