### ISSUE TITLE
Request Update: Release v0.5.2

### ISSUE THREAD

**Issue by kasi-x** [arnetheduck/nph#70]
Current latest nph release (v0.5.1) is not compatible with current latest stable version of nim (v2.0.4), as it only supports Nim v2.0.3.

Change #68 addresses this compatibility, but it is not included in v0.5.1. Could you please release a new version (v0.5.2) for solving this situation.

If you release v0.5.2 (or v0.6) from current master branch, the release note would be below one.

```
# What's Changed

- register vscode extension for nims, nimble in #67
- Add support for nim version 2.0.4 in #68

**Full Changelog:** https://github.com/arnetheduck/nph/compare/v0.5.1...v0.5.2
```

**Comment by kasi-x** [comment]
I found this discussion, I want to know what action need to solve this situation.
Should we make github action and some test case or find some different case from version update?
https://github.com/arnetheduck/nph/pull/68#discussion_r1596484539

**Comment by arnetheduck** [comment]
> I found this discussion and would like to know what actions are needed to resolve this situation. 

currently nph uses the same nim it was built with to check whether the resulting nim file is still valid after formatting - so if you format a file meant for nim 1.6 with nph, it could technically fail on 1.6 after formatitng even if it works with 2.0 (the parsing rules might change between nim releases).

So to resolve this, one needs to implement the correctness checker in such a way that it supports multiple nim versions regardless of which nim version was used to build nph, which is a non-trivial task.

**Comment by arnetheduck** [comment]
https://github.com/arnetheduck/nph/commit/b859830589aa0b630ba10288d3d53d585e1c8a62

**Comment by kasi-x** [comment]
Thank you for updating great oss.
